apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sa-web
  template:
    metadata:
      labels:
        app: sa-web
    spec:
      containers:
        - name: sa-web
          image: sa-web:latest
          env:
            - name: ANALYSIS_URL
              value: 'http://sa-logic:5000'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sa-web
spec:
  selector:
    app: sa-web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
