services:
  sa-logic:
    build: ./sa-logic
    ports:
      - '5000:5000'
    environment:
      - PYTHONUNBUFFERED=1

  sa-web:
    build: ./sa-web
    ports:
      - '8080:8080'
    environment:
      - ANALYSIS_URL=http://sa-logic:5000
    depends_on:
      - sa-logic

  sa-frontend:
    build: ./sa-frontend
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=http://sa-web:8080
    depends_on:
      - sa-web

networks:
  default:
    driver: bridge
